apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment-lb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-lb
  template:
    metadata:
      labels:
        app: my-app-lb
    spec:
      containers:
      - name: my-app-lb-container
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service-lb
  labels:
   app: my-app-lb
spec:
  type: LoadBalencer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: my-app-nodeport
