apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment-nodeport
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-nodeport
  template:
    metadata:
      labels:
        app: my-app-nodeport
    spec:
      containers:
      - name: my-app-container
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service-nodeport
  labels:
   app: my-app-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: my-app-nodeport
