apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Specifies that the volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 5Gi  # The amount of storage requested
  storageClassName: my-storage-class  # The StorageClass to use, if applicable