apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hintechnologies-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hintech
  template:
    metadata:
      labels:
        app: hintech
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
